-- Gebied B: sub-gebied vragen aanvullen tot 2 per sub per niveau

-- Eigenschappen: niv 2 (+1), niv 3 (+1), niv 4 (+2), niv 5 (+2)
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'eigenschappen', 'VD1_06.01', 2, 'meerkeuze', 'Pas de distributieve eigenschap toe: a·(b − c) = ?', '[{"label": "a·b − a·c", "waarde": "A"}, {"label": "a·b + a·c", "waarde": "B"}, {"label": "a·b − c", "waarde": "C"}, {"label": "a − b·c", "waarde": "D"}]'::jsonb, 'A', 'De distributieve eigenschap: a·(b−c) = a·b − a·c. De factor a wordt verdeeld over beide termen.', 'N4_D5_M00');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'eigenschappen', 'VD1_06.01', 3, 'meerkeuze', 'Toon aan dat delen in Z niet commutatief is met 12 en 3.', '[{"label": "12:3=4 en 3:12=0,25 — verschillend", "waarde": "A"}, {"label": "12:3=4 en 3:12=4 — gelijk", "waarde": "B"}, {"label": "12·3=36 en 3·12=36", "waarde": "C"}, {"label": "12−3=9 en 3−12=−9", "waarde": "D"}]'::jsonb, 'A', '12:3=4 maar 3:12=0,25. De resultaten zijn verschillend, dus delen is niet commutatief.', 'N4_D5_M00');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'eigenschappen', 'VD1_06.01', 4, 'meerkeuze', 'Wat is het symmetrisch element van 5 voor de optelling in Z?', '[{"label": "−5", "waarde": "A"}, {"label": "5", "waarde": "B"}, {"label": "0", "waarde": "C"}, {"label": "1/5", "waarde": "D"}]'::jsonb, 'A', 'Het symmetrisch element voor optelling is het tegengestelde: 5 + (−5) = 0.', 'N4_D5_M00');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, juist_antwoord, tolerantie, uitleg_html, bron_module) VALUES ('B', 'eigenschappen', 'VD1_06.01', 5, 'invul', 'Als a·b = 0, wat weet je dan over a en b? Kies uit: minstens een is 0 / beide zijn 0 / een is positief. Antwoord met 1, 2 of 3.', '1', 0, '1 = minstens een is 0. Dit is de nuleigenschap: een product is nul als minstens een van de factoren nul is.', 'N4_D5_M00');

-- Machten: niv 1 (+1), niv 4 (+1), niv 5 (+1)
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'machten', 'BV 06.03', 1, 'meerkeuze', 'Wat is de waarde van a^0 (met a ≠ 0)?', '[{"label": "1", "waarde": "A"}, {"label": "0", "waarde": "B"}, {"label": "a", "waarde": "C"}, {"label": "bestaat niet", "waarde": "D"}]'::jsonb, 'A', 'Elk getal (behalve 0) tot de macht 0 is 1. a^0 = 1.', 'N2_M05');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'machten', 'BV 06.03', 4, 'meerkeuze', 'Schrijf zonder negatieve exponent: 3·x^(-2)', '[{"label": "3/x^2", "waarde": "A"}, {"label": "1/3x^2", "waarde": "B"}, {"label": "−3x^2", "waarde": "C"}, {"label": "3x^2", "waarde": "D"}]'::jsonb, 'A', 'x^(-2) = 1/x^2. Dus 3·x^(-2) = 3/x^2. Alleen de x heeft een negatieve exponent.', 'N4_D5_M00');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'machten', 'BV 06.03', 5, 'meerkeuze', 'Vereenvoudig: (2a^3)^2 · a^(-4)', '[{"label": "4a^2", "waarde": "A"}, {"label": "2a^2", "waarde": "B"}, {"label": "4a^(-2)", "waarde": "C"}, {"label": "2a^5", "waarde": "D"}]'::jsonb, 'A', '(2a^3)^2 = 4a^6. 4a^6 · a^(-4) = 4a^(6−4) = 4a^2.', 'N4_D5_M00');

-- Volgorde: niv 1 (+1), niv 3 (+1)  
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, juist_antwoord, tolerantie, uitleg_html, bron_module) VALUES ('B', 'volgorde', 'BV1_06.01', 1, 'invul', 'Bereken: 3 + 4 · 2 = ?', '11', 0.001, 'Eerst vermenigvuldigen: 4·2 = 8. Dan optellen: 3 + 8 = 11. Het antwoord is NIET 14 (dat krijg je als je eerst optelt).', 'N1_M08');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, juist_antwoord, tolerantie, uitleg_html, bron_module) VALUES ('B', 'volgorde', 'BV 06.03', 3, 'invul', 'Bereken: 6 · (2 + 3) − 4^2', '14', 0.001, 'Haakjes: 2+3=5. Macht: 4^2=16. Vermenigvuldigen: 6·5=30. Aftrekken: 30−16=14.', 'N4_D5_M00');

-- Wortels: niv 1 (+1), niv 2 (+1), niv 3 (+1)
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, juist_antwoord, tolerantie, uitleg_html, bron_module) VALUES ('B', 'wortels', 'BV 06.03', 1, 'invul', 'Bereken: √81 = ?', '9', 0.001, '9^2 = 81, dus √81 = 9.', 'N2_M05');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, keuzes_json, juist_antwoord, uitleg_html, bron_module) VALUES ('B', 'wortels', 'BV 06.03', 2, 'meerkeuze', 'Vereenvoudig: √80', '[{"label": "4√5", "waarde": "A"}, {"label": "8√5", "waarde": "B"}, {"label": "2√20", "waarde": "C"}, {"label": "5√4", "waarde": "D"}]'::jsonb, 'A', '√80 = √(16·5) = √16 · √5 = 4√5.', 'N4_D5_M00');
INSERT INTO vragen (gebied, sub_gebied, leerplandoel, niveau, type, vraag_html, juist_antwoord, tolerantie, uitleg_html, bron_module) VALUES ('B', 'wortels', 'BV 06.03', 3, 'invul', 'Vereenvoudig: (√3)^2 + √12 · √3', '9', 0.001, '(√3)^2 = 3. √12·√3 = √36 = 6. 3 + 6 = 9.', 'N4_D5_M00');
